<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'id' => 1,
                'name' => 'jesu',
                'email' => 'mezi@mailinator.com',
                'email_verified_at' => null,
                'password' => '$2y$10$fUyB2Oi.63.zzbmYZPxS7eQlNDZn1b/sn6sPlEm0zK7NgrtRH.9f.',
                'remember_token' => null,
                'created_at' => '2025-10-07 22:28:43',
                'updated_at' => '2025-10-07 22:28:43',
                'mobile' => '1231231213213',
                'mobile_verified_at' => null,
                'iban' => null,
                'branch' => 'Voluptatem expedita',
                'tax_number' => '92221321kk',
                'cr_number' => '254123132l',
                'cr_document' => 'admin/assets/images/users/176015127150451.png',
                'location' => 'Nam fugiat tempor vo',
                'img' => 'admin/assets/images/users/175988332346772.png',
                'fcm_token' => null,
                'code' => null,
                'user_type' => 2,
                'deleted_at' => null,
                'is_activate' => 1,
                'report_id' => 1,
            ],
            [
                'id' => 2,
                'name' => 'ruvyrin',
                'email' => 'fyly@mailinator.com',
                'email_verified_at' => null,
                'password' => '$2y$10$WCIX5A8T2nbtJHWwwwFZIOSW1TK3ty/oQ9tCXSNe2fZ9C/.o5Z0P2',
                'remember_token' => null,
                'created_at' => '2025-10-07 22:31:27',
                'updated_at' => '2025-10-07 22:31:27',
                'mobile' => '98784654655',
                'mobile_verified_at' => null,
                'iban' => null,
                'branch' => null,
                'tax_number' => null,
                'cr_number' => null,
                'cr_document' => null,
                'location' => null,
                'img' => 'admin/assets/images/users/175988348799653.png',
                'fcm_token' => null,
                'code' => null,
                'user_type' => 1,
                'deleted_at' => null,
                'is_activate' => 1,
                'report_id' => 1,
            ],
            [
                'id' => 3,
                'name' => 'amr 4442',
                'email' => 'amr22@gmail.com',
                'email_verified_at' => '2025-10-17 21:00:23',
                'password' => '$2y$10$HYErtOa2j0NJcZCYqKkjGuesixtwA1K4XIQqi6TisxSx2kdZJRUz.',
                'remember_token' => null,
                'created_at' => '2025-10-11 00:07:27',
                'updated_at' => '2025-11-08 16:58:14',
                'mobile' => '+96612345678002',
                'mobile_verified_at' => '2025-10-17 21:00:23',
                'iban' => 'iban-data',
                'branch' => 'branch',
                'tax_number' => '123123132',
                'cr_number' => '123123123123',
                'cr_document' => null,
                'location' => 'location',
                'img' => 'admin/assets/images/users/176262829453862.png',
                'fcm_token' => 'cXmf-bClTg68yTEcnujtvu:APA91bFQ9uDF3lki7GPv2xaA73187SLjdsvP8hOs2c5hBsMbvLULn7Tvp2PMRSVmJlmEkkB9AWaCp-apPbLS_mUezF2pIfOuhg20Ic8J6m46TCP4M5Kl91M',
                'code' => null,
                'user_type' => 2,
                'deleted_at' => null,
                'is_activate' => 1,
                'report_id' => 1,
            ],
            [
                'id' => 4,
                'name' => 'amr 444',
                'email' => 'amr222@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$10$QmskJkeIaWyVPF8QsbewJel/dnzRKmxFqMYsPmGrAgToq.KFrZlyi',
                'remember_token' => null,
                'created_at' => '2025-10-11 00:44:45',
                'updated_at' => '2025-10-11 00:44:45',
                'mobile' => '+966123456780020',
                'mobile_verified_at' => null,
                'iban' => 'iban-data0',
                'branch' => null,
                'tax_number' => null,
                'cr_number' => null,
                'cr_document' => null,
                'location' => 'location location location',
                'img' => 'admin/assets/images/users/175988348799653.png',
                'fcm_token' => 'cXmf-bClTg68yTEcnujtvu:APA91bFQ9uDF3lki7GPv2xaA73187SLjdsvP8hOs2c5hBsMbvLULn7Tvp2PMRSVmJlmEkkB9AWaCp-apPbLS_mUezF2pIfOuhg20Ic8J6m46TCP4M5Kl91M',
                'code' => '1111',
                'user_type' => 1,
                'deleted_at' => null,
                'is_activate' => 1,
                'report_id' => 1,
            ],
            [
                'id' => 5,
                'name' => 'amr 4443',
                'email' => 'amr223@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$10$v0PsS8Sq43JnvilTajtXuutwrv7pdHyJ1KwBRdm8EO6AHhOMJJky2',
                'remember_token' => null,
                'created_at' => '2025-10-11 00:49:37',
                'updated_at' => '2025-10-11 00:49:37',
                'mobile' => '+966123456780023',
                'mobile_verified_at' => null,
                'iban' => 'iban-data3',
                'branch' => 'branch',
                'tax_number' => '123123132',
                'cr_number' => '123123123123',
                'cr_document' => null,
                'location' => 'location',
                'img' => null,
                'fcm_token' => 'drOWb72CTLmxu4AaJ_LbU6:APA91bFoprg_oWZbiHLefNSwRbtFUMX0u-W_xu4OcT8WIP24c70bNnR8jAMcqBVGXAhfoY7H6zxzvzzCCSDZcKKmGJ3J2mQej9ENsinfLPjgLt0Yf9Grx1M',
                'code' => '1111',
                'user_type' => 2,
                'deleted_at' => null,
                'is_activate' => 1,
                'report_id' => 1,
            ],
            [
                'id' => 6,
                'name' => 'amr 4444',
                'email' => 'amr224@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$10$Q1HwsTFaTFtdV5LiSb9on.tFDmZXQiqs/BX9d/.8qE3mHb5cMQlbO',
                'remember_token' => null,
                'created_at' => '2025-10-11 00:54:31',
                'updated_at' => '2025-10-11 00:54:31',
                'mobile' => '+966123456780024',
                'mobile_verified_at' => null,
                'iban' => 'iban-data4',
                'branch' => 'branch',
                'tax_number' => '123123132',
                'cr_number' => '123123123123',
                'cr_document' => 'admin/assets/images/users/176015127150451.png',
                'location' => 'location',
                'img' => null,
                'fcm_token' => 'cXmf-bClTg68yTEcnujtvu:APA91bFQ9uDF3lki7GPv2xaA73187SLjdsvP8hOs2c5hBsMbvLULn7Tvp2PMRSVmJlmEkkB9AWaCp-apPbLS_mUezF2pIfOuhg20Ic8J6m46TCP4M5Kl91M',
                'code' => '1111',
                'user_type' => 2,
                'deleted_at' => null,
                'is_activate' => 1,
                'report_id' => 1,
            ],
            [
                'id' => 7,
                'name' => 'amr 444499',
                'email' => 'amr22499@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$10$k4Sx6JkbnUf50NHxue3xi.nxVAtKz9CfXJ2W8aEA3KCWEHJFD2Pk.',
                'remember_token' => null,
                'created_at' => '2025-10-19 11:06:45',
                'updated_at' => '2025-10-19 11:06:45',
                'mobile' => '+966123456780099',
                'mobile_verified_at' => null,
                'iban' => 'iban-data499',
                'branch' => 'branch',
                'tax_number' => '123123132',
                'cr_number' => '123123123123',
                'cr_document' => null,
                'location' => 'location',
                'img' => null,
                'fcm_token' => 'cXmf-bClTg68yTEcnujtvu:APA91bFQ9uDF3lki7GPv2xaA73187SLjdsvP8hOs2c5hBsMbvLULn7Tvp2PMRSVmJlmEkkB9AWaCp-apPbLS_mUezF2pIfOuhg20Ic8J6m46TCP4M5Kl91M',
                'code' => '1111',
                'user_type' => 2,
                'deleted_at' => null,
                'is_activate' => 1,
                'report_id' => 1,
            ],
            [
                'id' => 21,
                'name' => 'hospital12@gmail.com',
                'email' => 'hospital12@gmail.com',
                'email_verified_at' => '2025-11-08 14:21:19',
                'password' => '$2y$10$Vdcra7/LqkvfkVir1fFTJuw8Q7C/AjpU8rfJ5VXbR77Wf1P2cBct2',
                'remember_token' => null,
                'created_at' => '2025-11-08 11:04:46',
                'updated_at' => '2025-11-08 11:04:46',
                'mobile' => '333333333',
                'mobile_verified_at' => '2025-11-08 14:21:27',
                'iban' => '12344321',
                'branch' => 'hospital 12',
                'tax_number' => null,
                'cr_number' => '12344321',
                'cr_document' => 'admin/assets/images/users/176260708676693.jpg',
                'location' => 'king fahd st. jidah, KSA',
                'img' => null,
                'fcm_token' => 'd-HVRtGMQj-XhuD0MNuhb0:APA91bHncj5OwckPEAJHpkRwW_-tAoKb_HfvgmVY5inNRcr5l8iXMd3fWSbSEulzcx2TjOSOob4rI0lQp0bFRrN6JyA21e4MN0jZTPiQZMbvQ8J5GvGeUEU',
                'code' => null,
                'user_type' => 1,
                'deleted_at' => null,
                'is_activate' => 1,
                'report_id' => 1,
            ],
            [
                'id' => 22,
                'name' => 'Upton Hutchinson',
                'email' => 'cozimy@mailinator.com',
                'email_verified_at' => null,
                'password' => '$2y$10$6jz7mZefjoO8TphZ8jPK8uagoIHHaxg4H6obnCAFmWuUhtkrIPk.2',
                'remember_token' => null,
                'created_at' => '2025-11-11 22:29:10',
                'updated_at' => '2025-11-11 22:29:10',
                'mobile' => '789654258',
                'mobile_verified_at' => null,
                'iban' => 'uuuu774hh55',
                'branch' => 'Nesciunt veniam fa',
                'tax_number' => '916',
                'cr_number' => '422',
                'cr_document' => 'admin/assets/images/users/176290735064382.png',
                'location' => 'Dolor rerum quia lab',
                'img' => null,
                'fcm_token' => null,
                'code' => '2759',
                'user_type' => 2,
                'deleted_at' => null,
                'is_activate' => 1,
                'report_id' => 1,
            ],
            [
                'id' => 23,
                'name' => 'Sandra Salas',
                'email' => 'casi@mailinator.com',
                'email_verified_at' => null,
                'password' => '$2y$10$di9XXI1oLDo0D//k74bcfuAX.PdTbfylEbvIRR89rfviNNkJ0geVG',
                'remember_token' => null,
                'created_at' => '2025-11-11 22:40:25',
                'updated_at' => '2025-11-11 22:40:25',
                'mobile' => '456456456',
                'mobile_verified_at' => null,
                'iban' => '987789987',
                'branch' => 'Ratione dolore rem e',
                'tax_number' => '166',
                'cr_number' => '820',
                'cr_document' => 'admin/assets/images/users/176290802559974.png',
                'location' => 'Quis incidunt aute',
                'img' => null,
                'fcm_token' => null,
                'code' => '3794',
                'user_type' => 1,
                'deleted_at' => null,
                'is_activate' => 1,
                'report_id' => 1,
            ],
            [
                'id' => 24,
                'name' => 'Xyla Allen',
                'email' => 'gyqegakiwu@mailinator.com',
                'email_verified_at' => null,
                'password' => '$2y$10$KC5w.F9joMjC8XcK6tONVe7Vbs5K0lAmHSqWaxcAEtY9u1zGO3J8G',
                'remember_token' => null,
                'created_at' => '2025-11-11 22:41:31',
                'updated_at' => '2025-11-11 22:41:31',
                'mobile' => '654789654',
                'mobile_verified_at' => null,
                'iban' => '98745632',
                'branch' => 'Voluptas et et vero',
                'tax_number' => '394',
                'cr_number' => '809',
                'cr_document' => 'admin/assets/images/users/176290809128052.png',
                'location' => 'Cupiditate id praese',
                'img' => null,
                'fcm_token' => null,
                'code' => '5689',
                'user_type' => 1,
                'deleted_at' => null,
                'is_activate' => 1,
                'report_id' => 1,
            ],
            [
                'id' => 25,
                'name' => 'Yardley Jarvis',
                'email' => 'zijaxe@mailinator.com',
                'email_verified_at' => null,
                'password' => '$2y$10$4zQnOfXHFr9/k/XQ2D9iVe5qYjwYtG4F2KfkEq4tPFpHxMOUltW56',
                'remember_token' => null,
                'created_at' => '2025-11-11 22:43:55',
                'updated_at' => '2025-11-11 22:43:55',
                'mobile' => '123213256',
                'mobile_verified_at' => null,
                'iban' => '541321655',
                'branch' => 'Dolore corporis quae',
                'tax_number' => '938',
                'cr_number' => '656',
                'cr_document' => 'admin/assets/images/users/176290823561035.png',
                'location' => 'Molestiae voluptatem',
                'img' => null,
                'fcm_token' => null,
                'code' => '2930',
                'user_type' => 2,
                'deleted_at' => null,
                'is_activate' => 1,
                'report_id' => 1,
            ],
            [
                'id' => 26,
                'name' => 'Leo Hale',
                'email' => 'seko@mailinator.com',
                'email_verified_at' => '2025-11-11 23:39:48',
                'password' => '$2y$10$zmVjbwnND9a7IQjZeB/8nOtoME.o/InPqiUt74YYwXrZ.AFw.PWKC',
                'remember_token' => null,
                'created_at' => '2025-11-11 23:22:38',
                'updated_at' => '2025-11-11 23:39:48',
                'mobile' => '963258963',
                'mobile_verified_at' => '2025-11-11 23:39:48',
                'iban' => 'Hic distinctio Quia',
                'branch' => 'Dolore ab esse magn',
                'tax_number' => '353',
                'cr_number' => '449',
                'cr_document' => 'admin/assets/images/users/176291055843755.png',
                'location' => 'Est dicta maxime qui',
                'img' => null,
                'fcm_token' => null,
                'code' => null,
                'user_type' => 2,
                'deleted_at' => null,
                'is_activate' => 1,
                'report_id' => 1,
            ],
            [
                'id' => 27,
                'name' => 'Kyra Mathis',
                'email' => 'doly@mailinator.com',
                'email_verified_at' => '2025-11-12 00:03:33',
                'password' => '$2y$10$EQ/XfkP41/3Xp1uMUSG7v.mACMfQ4Vztl2CRkmsXMgE9gBlN9A4jC',
                'remember_token' => null,
                'created_at' => '2025-11-11 23:47:08',
                'updated_at' => '2025-11-12 00:03:33',
                'mobile' => '8978976543',
                'mobile_verified_at' => '2025-11-12 00:03:33',
                'iban' => '424244211111',
                'branch' => 'Ullam commodo beatae',
                'tax_number' => '766',
                'cr_number' => '302',
                'cr_document' => 'admin/assets/images/users/176291202873933.png',
                'location' => 'Possimus adipisci q',
                'img' => null,
                'fcm_token' => null,
                'code' => null,
                'user_type' => 1,
                'deleted_at' => null,
                'is_activate' => 1,
                'report_id' => 1,
            ],
            [
                'id' => 28,
                'name' => 'Timon Crane',
                'email' => 'bybi@mailinator.com',
                'email_verified_at' => '2025-11-12 00:17:39',
                'password' => '$2y$10$N.7D1/QHyu1dUrYs2kz87OMrr950GpkT1dGClWR6tQAodTFUrVw1.',
                'remember_token' => null,
                'created_at' => '2025-11-12 00:15:34',
                'updated_at' => '2025-11-12 01:37:13',
                'mobile' => '7852148215',
                'mobile_verified_at' => '2025-11-12 00:17:39',
                'iban' => '9568566',
                'branch' => 'Non illum anim qui',
                'tax_number' => '729',
                'cr_number' => '823',
                'cr_document' => 'admin/assets/images/users/176291373362575.png',
                'location' => 'Quos nihil ipsum to',
                'img' => null,
                'fcm_token' => null,
                'code' => null,
                'user_type' => 1,
                'deleted_at' => null,
                'is_activate' => 1,
                'report_id' => 1,
            ],
        ]);
    }
}
